name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          pip install jupyter

      - name: Build project
        run: bundle exec jekyll build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./_site

      - name: Configure Git
        run: |
          git config --global user.name 'silvanayanzisun'
          git config --global user.email 'yanyan1025911978@gmail.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
